In [2]:
import pandas as pd
import geopandas as gpd

/home/dan/anaconda3/lib/python3.7/site-packages/geopandas/_compat.py:88: UserWarning: The Shapely GEOS version (3.6.2-CAPI-1.10.2 4d2925d6) is incompatible with the GEOS version PyGEOS was compiled with (3.8.1-CAPI-1.13.3). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string

In [3]:
foo = pd.read_csv('missing_tetra_density_species.csv')[17:]
foo

,Unnamed: 0,Unnamed: 0.1,binomial,Range,AdultBodyMass_g,Red List status,TrophicLevel,Order
17,368,399,Bubalus arnee,12946.169502,483500.485000,EN,Herbivore,CETARTIODACTYLA
18,373,407,Bunolagus monticularis,78511.544238,1750.010000,CR,Herbivore,LAGOMORPHA
19,392,430,Callithrix aurita,159614.292482,386.200000,VU,Omnivore,PRIMATES
20,393,431,Callithrix flaviceps,24732.630324,372.970000,EN,Omnivore,PRIMATES
21,395,433,Callithrix jacchus,943369.790314,290.210000,LC,Omnivore,PRIMATES
...,...,...,...,...,...,...,...,...
246,4345,4711,Thylamys pulchellus,339443.429774,30.607294,LC,NotAssigned,DIDELPHIMORPHIA
247,4376,4745,Trachypithecus johnii,16984.145886,10595.080000,VU,Omnivore,PRIMATES
248,4381,4751,Trachypithecus shortridgei,10597.022417,13182.000000,EN,Herbivore,PRIMATES
249,4412,4792,Tupaia chrysogaster,6002.771176,180.667000,EN,Omnivore,SCANDENTIA
250,4506,4895,Zaglossus bartoni,174288.769698,6500.000000,VU,Insectivore,MONOTREMATA

In [4]:
geo_data = gpd.read_file('TERRESTRIAL_MAMMALS/TERRESTRIAL_MAMMALS.shp').to_crs("EPSG:6933")
mammals_df_geo = gpd.GeoDataFrame(foo.merge(geo_data, on='binomial', how='left'))
mammals_df_geo = mammals_df_geo.reset_index()
mammals_df_geo = mammals_df_geo.dissolve(by='binomial').reset_index()

In [8]:
mammals_df_geo = mammals_df_geo.reset_index()
mammals_df_geo = mammals_df_geo.dissolve(by='binomial').reset_index()

In [11]:
mammals_df_geo = mammals_df_geo[mammals_df_geo.binomial!='Sus scrofa']
mammals_df_geo

,binomial,geometry,index,Unnamed: 0,Unnamed: 0.1,Range,AdultBodyMass_g,Red List status,TrophicLevel,Order,...,class,order_,family,genus,category,marine,terrestial,freshwater,SHAPE_Leng,SHAPE_Area
0,Bubalus arnee,"MULTIPOLYGON (((7853298.160 850113.371, 786343...",0,368,399,12946.169502,483500.485000,EN,Herbivore,CETARTIODACTYLA,...,MAMMALIA,CETARTIODACTYLA,BOVIDAE,Bubalus,EN,false,true,true,1.247280,0.060841
1,Bunolagus monticularis,"MULTIPOLYGON (((1982957.350 -4006414.427, 1987...",2,373,407,78511.544238,1750.010000,CR,Herbivore,LAGOMORPHA,...,MAMMALIA,LAGOMORPHA,LEPORIDAE,Bunolagus,CR,false,true,false,17.887275,4.353825
2,Callithrix aurita,"MULTIPOLYGON (((-3959420.645 -2693146.744, -39...",3,392,430,159614.292482,386.200000,VU,Omnivore,PRIMATES,...,MAMMALIA,PRIMATES,CALLITRICHIDAE,Callithrix,EN,false,true,false,29.580526,13.967139
3,Callithrix flaviceps,"POLYGON ((-3956381.327 -2440382.658, -3953177....",4,393,431,24732.630324,372.970000,EN,Omnivore,PRIMATES,...,MAMMALIA,PRIMATES,CALLITRICHIDAE,Callithrix,EN,false,true,false,7.427697,2.133323
4,Callithrix jacchus,"MULTIPOLYGON (((-3389659.511 -1123884.644, -33...",5,395,433,943369.790314,290.210000,LC,Omnivore,PRIMATES,...,MAMMALIA,PRIMATES,CALLITRICHIDAE,Callithrix,LC,false,true,false,59.054805,77.274202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Thylamys pulchellus,"POLYGON ((-6164646.229 -2776393.267, -6159536....",484,4345,4711,339443.429774,30.607294,LC,NotAssigned,DIDELPHIMORPHIA,...,MAMMALIA,DIDELPHIMORPHIA,DIDELPHIDAE,Thylamys,LC,false,true,false,24.153273,30.956895
230,Trachypithecus johnii,"MULTIPOLYGON (((7464352.867 1316169.917, 74696...",485,4376,4745,16984.145886,10595.080000,VU,Omnivore,PRIMATES,...,MAMMALIA,PRIMATES,CERCOPITHECIDAE,Trachypithecus,VU,false,true,false,9.677633,1.401625
231,Trachypithecus shortridgei,"POLYGON ((9462052.969 3340409.263, 9462202.061...",486,4381,4751,10597.022417,13182.000000,EN,Herbivore,PRIMATES,...,MAMMALIA,PRIMATES,CERCOPITHECIDAE,Trachypithecus,EN,false,true,false,4.638999,0.965515
232,Tupaia chrysogaster,"MULTIPOLYGON (((9671294.582 -355640.955, 96715...",487,4412,4792,6002.771176,180.667000,EN,Omnivore,SCANDENTIA,...,MAMMALIA,SCANDENTIA,TUPAIIDAE,Tupaia,VU,false,true,false,1.256730,0.050920
233,Zaglossus bartoni,"MULTIPOLYGON (((14461059.587 -1289224.383, 144...",491,4506,4895,174288.769698,6500.000000,VU,Insectivore,MONOTREMATA,...,MAMMALIA,MONOTREMATA,TACHYGLOSSIDAE,Zaglossus,VU,false,true,false,37.631848,14.153674

In [12]:
%run -m gen_data_for_tetra_density_model

In [ ]:
mammals_df_geo.apply(get_gridded_data, axis=1)

/home/dan/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:47: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

Bubalus_arnee done
Bunolagus_monticularis done

/home/dan/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:47: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

Callithrix_aurita done
Callithrix_flaviceps done

/home/dan/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:47: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

Callithrix_jacchus done
Callithrix_penicillata done

/home/dan/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:47: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

Callosciurus_finlaysonii done

/home/dan/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:47: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

Callosciurus_melanogaster done

In [ ]:
mammals_df_geo